---

  - name: Install rpm repo
    become: yes
    yum: name={{ zbx_server_repo_el7 }} state=present

  - name: Install zabbix-server
    become: yes
    yum: name={{ item }} state=present
    with_items:
      - zabbix-server-{{ database }}
      - zabbix-web-{{ database }}

  - name: Install linuxse manage
    become: yes
    yum: name=libselinux-python state=present