- name: Develop environment
  include: develop.yml
  when: env == "dev"

- name: Test environment
  include: test.yml
  when: env == "test"

- name: Daily environment
  include: daily.yml
  when: env == "daily"

- name: Production environment
  include: production.yml
  when: env == "prod"

