#!/usr/bin/perl
# Dmitry Maksimov dima_dm@hotmail.com
# ./$0 cisco 172.16.0.1 75 5 public 5 lab-cisco
# version 1.5 16.03.2011 add 64 bit counters
# version 2.0 19.10.2012 Zabbix 2.0
use Time::localtime;
use Net::SNMP;
$version = "2.0";
$hostname = shift;		# Switch hostname in Zabbix
$hostip   = shift;		# IP of the switch
$ptpct    = shift;		# Port trigger will fire at this % load
				#     = 0 for no port triggers
$mem_ptpct= shift;		# Mem trigger will fire at this %
$cstring  = shift;		# Switch SNMP community string
$slow	  = shift;		# Delay factor for all items
@groups   = @ARGV;		# Host groups in Zabbix

unless (defined($hostip)) {
	print "$0 Version $version\n";
        print "Usage: $0 HOSTNAME IP [PORTLOAD] [MEMLOAD] [COMMUNITY] [MINUTES] [GROUPS]\n";
        print "Host name and IP are required parameters\n";
        print "Example: $0 localhost 127.0.0.1 75 5 public 5 lab-cisco\n";
        exit;
}

$hostname="Template_".$hostname;
unless (defined($ptpct))	{$ptpct   = 75};
unless (defined($mem_ptpct))	{$mem_ptpct = 5};
unless (defined($cstring))	{$cstring = 'public'};
unless (defined($slow))		{$slow	  = 5};
unless (defined(@groups))	{@groups  =('Cisco')};

print "Generated by $0 Version $version\n";
print "\nHost:\t\t$hostname\nIP:\t\t$hostip\nPercent:\t$ptpct\nComm string:\t$cstring\n";
print "Slow:\t\t$slow\nGroups:\t\t$groups[0]\n";
#print "OK?";
#$ok = <>;
#chomp $ok;
#unless ($ok eq 'Y') {exit};

$slow60   = ( 60*$slow );
$slow180  = ( 180*$slow );
$slow300  = ( 300*$slow );
$slow600  = ( 600*$slow );
$slow720  = ( 720*$slow );
$slow3600 = ( 3600*$slow );
$slow86400= ( 86400*$slow );


sub get_dt() {
	
	my $yr = localtime->year() - 100;
	my $mn = localtime->mon() + 1;
	my $dy = localtime->mday();
	my $hr = localtime->hour();
	my $mi = localtime->min();
	$dt = sprintf("%2.2d.%2.2d.%2.2d",$dy,$mn,$yr);
	$tm = sprintf("%2.2d.%2.2d",$hr,$mi);
	$dtm = sprintf("%2.2d%2.2d%2.2d%2.2d%2.2d",$yr,$mn,$dy,$hr,$mi);	
}

sub start_snmp() {
	
   ($session, $error) = Net::SNMP->session(
                           -hostname      => $hostip,
                           -port          => 161,
                           -version       => 2,
                           -community     => $cstring
                        );
   if (!defined($session)) {
      printf("ERROR: %s.\n", $error);
      exit 1;
   }
	
}

sub numerically { $a <=> $b;}

sub get_ifTable() {

	$ifindex = '.1.3.6.1.2.1.2.2.1.1';
	$ifAlias  = '.1.3.6.1.2.1.2.2.1.2';
	$ifdesc  = '.1.3.6.1.2.1.31.1.1.1.18';
	$iftype  = '.1.3.6.1.2.1.2.2.1.3';
	$ifspeed = '.1.3.6.1.2.1.2.2.1.5';
	start_snmp();
	my @columns = ($ifindex, $ifdesc,$iftype,$ifspeed,$ifAlias);
	$iftable = $session->get_entries(-columns => \@columns);
	unless (defined($iftable)) {
		printf("ERROR: %s.\n", $session->error);
		exit 1;
	}
	foreach $k (keys %$iftable) {
		print "$k\n";
	}
	$session->close();	
}

sub get_ports() {

	$ifNumber = '.1.3.6.1.2.1.2.1.0';
	$result = $session->get_request(
		-varbindlist => [$ifNumber]
	);

	$numports = $result->{$ifNumber};
	print "Num Ports: $numports\n";
	$np = 0;
	$in = 0;
	@ports = ();
	foreach $k (keys %$iftable) {
		unless($k =~ /^$ifindex/) {next};
		$r = $$iftable{$k};
		$np++;
		print "Port Index $np:$r\n";
		push @ports, $r;
	}
	@ports = sort numerically @ports;
	$max_port = $ports[$#ports];
	$len_port = int(log($max_port)/log(10)) + 1;
	print "Max Port: $max_port  $len_port\n";
}

sub get_fan() {
	$ciscoEnvMonFanState='.1.3.6.1.4.1.9.9.13.1.4.1.3';
	my $k;
	my @fan;
	my $num=0;
	start_snmp();
	my @columns = ($ciscoEnvMonFanState);
	$iffan = $session->get_entries(-columns => \@columns);
	unless (defined($iffan)) {
                printf("Fan not fountd. ERROR: %s.\n", $session->error);
        }
	foreach $k (keys %$iffan) {
		$num++;
                print "FAN_$num $k\n";
		push @fan, $k;
        }
	print "\n";
        $session->close();
	return @fan;
}

sub check_64bit_counters_support() {
       my $ifHCInOctets='.1.3.6.1.2.1.31.1.1.1.6';
       my $ifHCOutOctets='.1.3.6.1.2.1.31.1.1.1.10';
       my $use_64bit_counters;	
	start_snmp();
        my @columns = ($ifHCInOctets,$ifHCOutOctets);
        $iffan = $session->get_entries(-columns => \@columns);
        unless (defined($iffan)) {
                printf("This device don't support 64bit counters. ERROR: %s.\n", $session->error);
		$use_64bit_counters="false";
        } else  {
		print "This device support 64bit counters.\n";
		$use_64bit_counters="true";
		}	
        $session->close();
        return $use_64bit_counters;
}

my $use_64bit_counters=check_64bit_counters_support();
get_dt();
open XML, ">$hostname.xml";

print XML <<EOF1;
<?xml version="1.0"?>
<zabbix_export version="1.0" date="$dt" time="$tm">
	<hosts>
		<host name="$hostname">
			<useip>1</useip>
			<ip>$hostip</ip>
			<port>10050</port>
			<groups>
EOF1
foreach $group (@groups) {print XML "\t\t\t\t<group>$group</group>\n"};
print XML <<EOF2;
			</groups>
			<items>
				<item type="4" key="sysDescr" value_type="4">
					<description>Description</description>
					<delay>86400</delay>
					<history>7</history>
					<trends>365</trends>
					<status>0</status>
					<data_type>0</data_type>
					<multiplier>0</multiplier>
					<delta>0</delta>
					<formula>1</formula>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.2.1.1.1.0</snmp_oid>
					<snmp_port>161</snmp_port>
					<applications>
						<application>Availability</application>
					</applications>
				</item>

				<item type="4" key="sysUpTimeInstance" value_type="3">
                                        <description>sysUpTime</description>
                                        <delay>$slow180</delay>
                                        <history>7</history>
                                        <trends>365</trends>
					<multiplier>1</multiplier>
					<formula>0.01</formula>
                                        <units>sec</units>
                                        <snmp_community>$cstring</snmp_community>
                                        <snmp_oid>1.3.6.1.2.1.1.3.0</snmp_oid>
                                        <snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                                </item>
				<item type="4" key="ipForwDatagrams" value_type="3">
					<description>ipForwDatagrams - number of packets to forward</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Packet/sec</units>
					<delta>1</delta>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>1.3.6.1.2.1.4.6.0</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="ipOutNoRoutes" value_type="3">
					<description>ipOutNoRoutes - discard caused no-route</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Packet/sec</units>
					<delta>1</delta>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>1.3.6.1.2.1.4.12.0</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="ipInDiscards" value_type="3">
					<description>ipInDiscards - discards on input interfaces</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Packet/sec</units>
					<delta>1</delta>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>1.3.6.1.2.1.4.8.0</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="ipOutDiscards" value_type="3">
					<description>ipOutDiscards - discards on output interfaces</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Packet/sec</units>
					<delta>1</delta>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>1.3.6.1.2.1.4.11.0</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
                                <item type="4" key="Cpu" value_type="3">
                                        <description>% CPU</description>
                                        <delay>$slow60</delay>
                                        <history>7</history>
                                        <trends>365</trends>
                                        <formula>1</formula>
                                        <snmp_community>$cstring</snmp_community>
                                        <snmp_oid>.1.3.6.1.4.1.9.2.1.56.0</snmp_oid>
                                        <snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                                </item>
				<item type="4" key="cpmCPUTotal1minRev" value_type="3">
					<description>CPU Utilization avg last 1 min</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.7.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="cpmCPUTotal5minRev" value_type="3">
					<description>CPU Utilization avg last 5 min</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.8.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="cpmCPUMonIntervalValue" value_type="3">
					<description>CPU Utilization avg last 5 sec</description>
					<delay>$slow60</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.109.1.1.1.1.10.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
				<item type="4" key="processorRam" value_type="3">
					<description>Memory Total</description>
					<delay>$slow3600</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Byte</units>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.3.6.6.0</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>

				<item type="4" key="ciscoMemoryPoolLargestFree" value_type="3">
					<description>Memory Pool Largest Free</description>
					<delay>$slow300</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Byte</units>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.48.1.1.1.7.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>

				<item type="4" key="ciscoMemoryPoolFree" value_type="3">
					<description>Memory Free</description>
					<delay>$slow300</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Byte</units>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.48.1.1.1.6.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                        	</item>
				
				<item type="4" key="ciscoMemoryPoolUsed" value_type="3">
					<description>Memory Used</description>
					<delay>$slow300</delay>
					<history>7</history>
					<trends>365</trends>
					<formula>1</formula>
					<units>Byte</units>
					<snmp_community>$cstring</snmp_community>
					<snmp_oid>.1.3.6.1.4.1.9.9.48.1.1.1.5.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                        	</item>
				
                                <item type="4" key="ciscoEnvMonTemperatureStatusValue" value_type="3">
                                        <description>Temperature in C</description>
                                        <delay>$slow600</delay>
                                        <history>7</history>
                                        <trends>365</trends>
                                        <formula>1</formula>
                                        <units>C</units>
                                        <snmp_community>$cstring</snmp_community>
                                        <snmp_oid>.1.3.6.1.4.1.9.9.13.1.3.1.3.1</snmp_oid>
                                        <snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                                </item>
				
                                <item type="4" key="CiscoEnvMonState" value_type="3">
                                        <description>Temperature State</description>
                                        <delay>$slow600</delay>
                                        <history>7</history>
                                        <trends>365</trends>
                                        <formula>1</formula>
                                        <units></units>
                                        <snmp_community>$cstring</snmp_community>
                                        <snmp_oid>.1.3.6.1.4.1.9.9.13.1.3.1.6.1</snmp_oid>
                                        <snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
                                </item> 

				<item type="3" key="icmpping" value_type="3">
					<description>Simple_Ping</description>
					<delay>60</delay>
					<history>1</history>
					<trends>365</trends>
					<formula>1</formula>
					<snmp_community>public</snmp_community>
					<snmp_oid>interfaces.ifTable.ifEntry.ifInOctets.1</snmp_oid>
					<snmp_port>161</snmp_port>
                                        <applications>
                                          <application>Availability</application>
                                        </applications>
				</item>
EOF2
@fan=get_fan();
$num=0;
foreach $i (@fan)
{
$num++;
print XML "\t\t\t\t<item type=\"4\" key=\"FAN_$num\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>FAN $num status</description>\n";
print XML "\t\t\t\t\t<delay>$slow720</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>$i</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>Availability</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";
} 
get_ifTable();
get_ports();

foreach $port (@ports) {
$type = $$iftable{$iftype.'.'.$port};
if ($type ==   1) {next};
$portdesc = $$iftable{$ifdesc.'.'.$port};
$portdesc =~ s/&/&amp;/g;
$portdesc =~ s/</&lt;/g;
$portdesc =~ s/>/&gt;/g;
$portalias=$$iftable{$ifAlias.'.'.$port};
$portalias_short = $portalias;
$portalias_short =~ s/\/.*//g;
$portkey = $portalias;
$portkey =~ s#[^a-zA-Z0-9_]#_#g;
$sport = sprintf ("%${len_port}.${len_port}d",$port);
print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_Description\" value_type=\"1\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias Description $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow86400</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<formula>1</formula>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.2.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_InOctets\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias InOctets $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>bps</units>\n";
print XML "\t\t\t\t\t<formula>8</formula>\n";
print XML "\t\t\t\t\t<multiplier>1</multiplier>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") 
 {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.6.$port</snmp_oid>\n";
 } else
     {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.10.$port</snmp_oid>\n";
     }
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_InUcastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias InUcastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") 
 {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.7.$port</snmp_oid>\n";
 } else
     {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.11.$port</snmp_oid>\n";
     }
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_ifInMulticastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias ifInMulticastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.8.$port</snmp_oid>\n";
} 
else {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.2.$port</snmp_oid>\n";
}
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_ifInBroadcastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias ifInBroadcastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.9.$port</snmp_oid>\n";
} 
else {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.3.$port</snmp_oid>\n";
}
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_OutUcastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias OutUcastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true")
 {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.11.$port</snmp_oid>\n";
 } else
     {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.17.$port</snmp_oid>\n";
     }
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_ifOutMulticastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias ifOutMulticastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.12.$port</snmp_oid>\n";
} 
else {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.4.$port</snmp_oid>\n";
}
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_ifOutBroadcastPkts\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias ifOutBroadcastPkts $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>pps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true") {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.13.$port</snmp_oid>\n";
} 
else {
  print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.5.$port</snmp_oid>\n";
}
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_InErrors\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias InErrors $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<delta>2</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.14.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_InCRC\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias InCRC $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<delta>2</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.4.1.9.2.2.1.1.12.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_OutOctets\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias OutOctets $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow60</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>bps</units>\n";
print XML "\t\t\t\t\t<delta>1</delta>\n";
print XML "\t\t\t\t\t<formula>8</formula>\n";
print XML "\t\t\t\t\t<multiplier>1</multiplier>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
if ($use_64bit_counters eq "true")
 {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.31.1.1.1.10.$port</snmp_oid>\n";
 } else
     {
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.16.$port</snmp_oid>\n";
     }
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_OutErrors\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias OutErrors $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<delta>2</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.20.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_Collisions\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias Collisions $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<delta>2</delta>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.4.1.9.2.2.1.1.25.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_Speed\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias Speed $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<units>bps</units>\n";
print XML "\t\t\t\t\t<formula>1</formula>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.5.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_OperStatus\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias OperStatus $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<formula>1</formula>\n";
print XML "\t\t\t\t\t<valuemap>Port Status</valuemap>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.8.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";

print XML "\t\t\t\t<item type=\"4\" key=\"Port_$portkey\_AdminStatus\" value_type=\"3\">\n";
print XML "\t\t\t\t\t<description>Port $sport $portalias AdminStatus $portdesc</description>\n";
print XML "\t\t\t\t\t<delay>$slow600</delay>\n";
print XML "\t\t\t\t\t<history>7</history>\n";
print XML "\t\t\t\t\t<trends>365</trends>\n";
print XML "\t\t\t\t\t<formula>1</formula>\n";
print XML "\t\t\t\t\t<valuemap>Port Status</valuemap>\n";
print XML "\t\t\t\t\t<snmp_community>$cstring</snmp_community>\n";
print XML "\t\t\t\t\t<snmp_oid>.1.3.6.1.2.1.2.2.1.7.$port</snmp_oid>\n";
print XML "\t\t\t\t\t<snmp_port>161</snmp_port>\n";
print XML "\t\t\t\t\t<applications>\n";
print XML "\t\t\t\t\t\t\t<application>$portalias_short</application>\n";
print XML "\t\t\t\t\t</applications>\n";
print XML "\t\t\t\t</item>\n";
}
print XML "\t\t\t</items>\n";
print XML "\t\t\t<triggers>\n";
$num=0;
foreach $i (@fan)
{
$num++;
	print XML "\t\t\t\t<trigger>\n";
        print XML "\t\t\t\t\t<description>FAN $num failed</description>\n";
        print XML "\t\t\t\t\t<expression>{$hostname:FAN_$num.last(0)}#1</expression>\n";
        print XML "\t\t\t\t\t<priority>2</priority>\n";
        print XML "\t\t\t\t\t<status>0</status>\n";
        print XML "\t\t\t\t\t<comments>
        FAN_$num Failed
        </comments>\n";
        print XML "\t\t\t\t</trigger>\n";
}
$fact = $ptpct/100;
foreach $port (@ports) {
	$type = $$iftable{$iftype.'.'.$port};
	if ($type ==   1) {next};
	$sport = sprintf ("%3.3d",$port);
	$portdesc = $$iftable{$ifdesc.'.'.$port};
	$portdesc =~ s/&/&amp;/g;
	$portdesc =~ s/</&lt;/g;
	$portdesc =~ s/>/&gt;/g;
	$speed = $$iftable{$ifspeed.'.'.$port};
	$cspeed = $ptpct*$speed/100;
	$portalias=$$iftable{$ifAlias.'.'.$port};
$portkey = $portalias;
$portkey =~ s#[^a-zA-Z0-9_]#_#g;
	
   if ($ptpct != 0) {
	print XML "\t\t\t\t<trigger>\n";
	print XML "\t\t\t\t\t<description>[Port $portalias InOctets] $sport $portdesc InOctets Threshold Exceeded</description>\n";
	print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_InOctets.min(#4)}&gt;$fact*{$hostname:Port_$portkey\_Speed.max(#2)} &amp; {$hostname:Port_$portkey\_Speed.max(#2)}#0</expression>\n";
	print XML "\t\t\t\t\t<priority>4</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
	print XML "\t\t\t\t\t<comments>
Port speed $speed bps
Threshold = $ptpct\%
</comments>\n";
	print XML "\t\t\t\t</trigger>\n";

	print XML "\t\t\t\t<trigger>\n";
        print XML "\t\t\t\t\t<description>[Port $portalias InErrors] $sport $portdesc InErrors on Interface </description>\n";
        print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_InErrors.last(0)}&gt;0</expression>\n";
        print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
        print XML "\t\t\t\t\t<comments>
        InErrors on interface
        </comments>\n";
        print XML "\t\t\t\t</trigger>\n";

        print XML "\t\t\t\t<trigger>\n";
        print XML "\t\t\t\t\t<description>[Port $portalias InCRC] $sport $portdesc InCRC error on Interface </description>\n";
        print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_InCRC.last(0)}&gt;0</expression>\n";
        print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
        print XML "\t\t\t\t\t<comments>
        InCRC error on interface
        </comments>\n";
        print XML "\t\t\t\t</trigger>\n";

	print XML "\t\t\t\t<trigger>\n";
	print XML "\t\t\t\t\t<description>[Port $portalias OutOctets] $sport $portdesc OutOctets Threshold Exceeded</description>\n";
	print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_OutOctets.min(#4)}&gt;$fact*{$hostname:Port_$portkey\_Speed.max(#2)} &amp; {$hostname:Port_$portkey\_Speed.max(#2)}#0</expression>\n";
	print XML "\t\t\t\t\t<priority>4</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
	print XML "\t\t\t\t\t<comments>Port speed $speed bps</comments>\n";
	print XML "\t\t\t\t</trigger>\n";


        print XML "\t\t\t\t<trigger>\n";
        print XML "\t\t\t\t\t<description>[Port $portalias OutErrors] $sport $portdesc OutErrors on Interface </description>\n";
        print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_OutErrors.last(0)}&gt;0</expression>\n";
        print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
        print XML "\t\t\t\t\t<comments>
        OutErrors on interface
        </comments>\n";
        print XML "\t\t\t\t</trigger>\n";

        print XML "\t\t\t\t<trigger>\n";
        print XML "\t\t\t\t\t<description>[Port $portalias Collisions] $sport $portdesc Collisions on Interface </description>\n";
        print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_Collisions.last(0)}&gt;0</expression>\n";
        print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
        print XML "\t\t\t\t\t<comments>
        Collisions on interface
        </comments>\n";
        print XML "\t\t\t\t</trigger>\n";


	print XML "\t\t\t\t<trigger>\n";
	print XML "\t\t\t\t\t<description>[Port $portalias AdminStatus] $sport $portdesc administrative status has changed</description>\n";
	print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_AdminStatus.delta(#2)}#0</expression>\n";
	print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
	print XML "\t\t\t\t</trigger>\n";
   }	
	print XML "\t\t\t\t<trigger>\n";
	print XML "\t\t\t\t\t<description>[Port $portalias OperStatus] $sport $portdesc status has changed</description>\n";
	print XML "\t\t\t\t\t<expression>{$hostname:Port_$portkey\_OperStatus.delta(#2)}#0</expression>\n";
	print XML "\t\t\t\t\t<priority>1</priority>\n";
	print XML "\t\t\t\t\t<status>0</status>\n";
	print XML "\t\t\t\t</trigger>\n";
}
$mem_fact=$mem_ptpct/100;
print XML <<EOF3;

				<trigger>
					<description>$hostname CPU Over $ptpct %</description>
					<expression>{$hostname:Cpu.min(90)}&gt;$ptpct</expression>
					<priority>4</priority>
					<status>0</status>
					<comments>$hostname has had a CPU Utilization above $ptpct % for 3 samples taken in the last 1 minute 30 seconds.</comments>
				</trigger>
				
				<trigger>
                                        <description>$hostname SNMP Failed</description>
                                        <expression>{$hostname:cpmCPUMonIntervalValue.nodata(14400)}=1</expression>
                                        <priority>4</priority>
					<status>0</status>
                                        <comments>$hostname SNMP Failed. Check configuration, ACL.</comments>
                                </trigger>
				
				<trigger>
					<description>Memory Free &lt; $mem_ptpct %</description>
					<type>0</type>
					<expression>{$hostname:ciscoMemoryPoolFree.min(10)}/{$hostname:processorRam.last(0)}&lt; $mem_fact</expression>
					<url></url>
					<status>0</status>
					<priority>3</priority>
					<comments>Memory Free &lt; $mem_ptpct %</comments>
				</trigger>

                                <trigger>
                                        <description>$hostname High Temperature </description>
                                        <expression>{$hostname:CiscoEnvMonState.last(0)}&gt;1 &amp; {$hostname:CiscoEnvMonState.last(0)}&lt;5</expression>
                                        <priority>4</priority>
					<status>0</status>
                                        <comments>$hostname High Temperature. Possible values:
1:normal
2:warning
3:critical
4:shutdown
5:notPresent
6:notFunctioning</comments>
                                </trigger>

				<trigger>
					<description>$hostname is Unreachable</description>
					<expression>{$hostname:icmpping.max(90)}=0</expression>
					<priority>4</priority>
					<status>0</status>
					<comments>Can not Ping $hostname 3 times in last 1 minute 30</comments>
				</trigger>

				<trigger>
                                        <description>$hostname reloaded</description>
                                        <expression>{$hostname:sysUpTimeInstance.last(0)}&lt;$slow720</expression>
                                        <priority>2</priority>
                                        <status>0</status>
                                        <comments>$hostname reloaded</comments>
                                </trigger>

EOF3

print XML "\t\t\t</triggers>\n";

print XML "\t\t\t<graphs>\n";
foreach $port (@ports) {
$type = $$iftable{$iftype.'.'.$port};
if ($type ==   1) {next};
$portdesc = $$iftable{$ifdesc.'.'.$port};
$portdesc =~ s/&/&amp;/g;
$portdesc =~ s/</&lt;/g;
$portdesc =~ s/>/&gt;/g;
$portalias=$$iftable{$ifAlias.'.'.$port};
$portkey = $portalias;
$portkey =~ s#[^a-zA-Z0-9_]#_#g;
$sport = sprintf ("%${len_port}.${len_port}d",$port);
print XML "\t\t\t\t<graph name=\"[Port $portalias] $sport $portdesc\" width=\"900\" height=\"400\">\n";
print XML <<EOF4;
					<yaxistype>0</yaxistype>
					<show_work_period>0</show_work_period>
					<show_triggers>0</show_triggers>
					<graphtype>0</graphtype>
					<ymin_type>1</ymin_type>
					<ymax_type>0</ymax_type>
					<ymin_item_key></ymin_item_key>
					<ymax_item_key></ymax_item_key>
					<yaxismin>0.0000</yaxismin>
					<yaxismax>100.0000</yaxismax>
					<show_legend>0</show_legend>
					<show_3d>0</show_3d>
					<percent_left>0.0000</percent_left>
					<percent_right>0.0000</percent_right>
					<graph_elements>
EOF4
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_OutOctets\">\n";
print XML <<EOF5;
							<drawtype>1</drawtype>
							<sortorder>0</sortorder>
							<color>009900</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>4</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
EOF5
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_InOctets\">\n";
print XML <<EOF6;
							<drawtype>2</drawtype>
							<sortorder>0</sortorder>
							<color>000099</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>4</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
				        </graph_elements>
					</graph>
EOF6
print XML "\t\t\t\t<graph name=\"[Port Packets $portalias] $sport $portdesc\" width=\"900\" height=\"400\">\n";
print XML <<EOF14;
                                        <yaxistype>0</yaxistype>
                                        <show_work_period>0</show_work_period>
                                        <show_triggers>0</show_triggers>
                                        <graphtype>0</graphtype>
                                        <ymin_type>1</ymin_type>
                                        <ymax_type>0</ymax_type>
                                        <ymin_item_key></ymin_item_key>
                                        <ymax_item_key></ymax_item_key>
                                        <yaxismin>0.0000</yaxismin>
                                        <yaxismax>100.0000</yaxismax>
                                        <show_legend>0</show_legend>
                                        <show_3d>0</show_3d>
                                        <percent_left>0.0000</percent_left>
                                        <percent_right>0.0000</percent_right>
                                        <graph_elements>
EOF14
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_InUcastPkts\">\n";
print XML <<EOF15;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>0</sortorder>
                                                        <color>009900</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
EOF15
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_OutUcastPkts\">\n";
print XML <<EOF16;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>1</sortorder>
                                                        <color>000099</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
EOF16
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_ifInBroadcastPkts\">\n";
print XML <<EOF17;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>2</sortorder>
                                                        <color>AA00AA</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
EOF17
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_ifOutBroadcastPkts\">\n";
print XML <<EOF18;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>3</sortorder>
                                                        <color>880000</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
EOF18
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_ifInMulticastPkts\">\n";
print XML <<EOF19;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>4</sortorder>
                                                        <color>000000</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
EOF19
print XML "\t\t\t\t\t\t<graph_element item=\"$hostname:Port_$portkey\_ifOutMulticastPkts\">\n";
print XML <<EOF20;
                                                        <drawtype>2</drawtype>
                                                        <sortorder>5</sortorder>
                                                        <color>888800</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>4</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element> 
					</graph_elements>
				</graph>
EOF20
}
print XML <<EOF7;
				<graph name="[RouterPerformance] - Total forwarded/dropped packets" width="900" height="400">
					<yaxistype>2</yaxistype>
					<show_work_period>0</show_work_period>
					<show_triggers>0</show_triggers>
					<graphtype>0</graphtype>
					<ymin_type>1</ymin_type>
					<ymax_type>0</ymax_type>
					<ymin_item_key></ymin_item_key>
					<ymax_item_key></ymax_item_key>
					<yaxismin>0.0000</yaxismin>
					<yaxismax>100.0000</yaxismax>
					<show_legend>0</show_legend>
					<show_3d>0</show_3d>
					<percent_left>0.0000</percent_left>
					<percent_right>0.0000</percent_right>
                                        <graph_elements>
						<graph_element item="$hostname:ipForwDatagrams">
							<drawtype>5</drawtype>
							<sortorder>0</sortorder>
							<color>009900</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
							<graph_element item="$hostname:ipInDiscards">
							<drawtype>5</drawtype>
							<sortorder>0</sortorder>
							<color>990000</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
                                                <graph_element item="$hostname:ipOutDiscards">
							<drawtype>5</drawtype>
							<sortorder>0</sortorder>
							<color>990099</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:ipOutNoRoutes">
							<drawtype>5</drawtype>
							<sortorder>0</sortorder>
							<color>FFFF00</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
					</graph_elements>
				</graph>

				<graph name="CPU LOAD %" width="900" height="400">
					<ymin_type>1</ymin_type>
					<ymax_type>0</ymax_type>
					<ymin_item_key></ymin_item_key>
					<ymax_item_key></ymax_item_key>
					<show_work_period>0</show_work_period>
					<show_triggers>0</show_triggers>
					<graphtype>0</graphtype>
					<yaxismin>0.0000</yaxismin>
					<yaxismax>100.0000</yaxismax>
					<show_legend>0</show_legend>
					<show_3d>0</show_3d>
					<percent_left>0.0000</percent_left>
					<percent_right>0.0000</percent_right>
					<graph_elements>
						<graph_element item="$hostname:cpmCPUTotal5minRev">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>EEEE00</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:cpmCPUTotal1minRev">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>EE0000</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:cpmCPUMonIntervalValue">
							<drawtype>2</drawtype>
							<sortorder>3</sortorder>
							<color>009900</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
					</graph_elements>
				</graph>

				<graph name="Memory" width="900" height="400">
					<yaxistype>2</yaxistype>
					<show_work_period>0</show_work_period>
					<show_triggers>1</show_triggers>
					<graphtype>0</graphtype>
					<ymin_type>1</ymin_type>
					<ymax_type>0</ymax_type>
					<ymin_item_key></ymin_item_key>
					<ymax_item_key></ymax_item_key>
					<yaxismin>0.0000</yaxismin>
					<yaxismax>100.0000</yaxismax>
					<show_legend>0</show_legend>
					<show_3d>0</show_3d>
					<percent_left>0.0000</percent_left>
					<percent_right>0.0000</percent_right>
					<graph_elements>
						<graph_element item="$hostname:processorRam">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>FF0000</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:ciscoMemoryPoolUsed">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>EEEE00</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:ciscoMemoryPoolFree">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>009900</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
						<graph_element item="$hostname:ciscoMemoryPoolLargestFree">
							<drawtype>0</drawtype>
							<sortorder>0</sortorder>
							<color>0000CC</color>
							<yaxisside>0</yaxisside>
							<calc_fnc>2</calc_fnc>
							<type>0</type>
							<periods_cnt>5</periods_cnt>
						</graph_element>
					</graph_elements>
				</graph>

                               <graph name="Temperature" width="900" height="400">
                                        <yaxistype>2</yaxistype>
                                        <show_work_period>0</show_work_period>
                                        <show_triggers>0</show_triggers>
                                        <graphtype>0</graphtype>
					<ymin_type>1</ymin_type>
					<ymax_type>0</ymax_type>
					<ymin_item_key></ymin_item_key>
					<ymax_item_key></ymax_item_key>
                                        <yaxismin>0.0000</yaxismin>
                                        <yaxismax>100.0000</yaxismax>
                                        <show_legend>0</show_legend>
                                        <show_3d>0</show_3d>
                                        <percent_left>0.0000</percent_left>
                                        <percent_right>0.0000</percent_right>
                                        <graph_elements>
                                                <graph_element item="$hostname:ciscoEnvMonTemperatureStatusValue">
                                                        <drawtype>0</drawtype>
                                                        <sortorder>0</sortorder>
                                                        <color>009900</color>
                                                        <yaxisside>0</yaxisside>
                                                        <calc_fnc>2</calc_fnc>
                                                        <type>0</type>
                                                        <periods_cnt>5</periods_cnt>
                                                </graph_element>
                                        </graph_elements>
                                </graph>

EOF7
print XML "\t\t\t</graphs>\n";
print XML "\t\t</host>\n";
print XML "\t</hosts>\n";
print XML "\t<dependencies>\n";
print XML "\t\t<dependency description=\"$hostname CPU Over 75 % the last 1 min\">\n";
print XML "\t\t\t<depends>$hostname CPU Over 75 % the last 5 min</depends>\n";
print XML "\t\t</dependency>\n";
print XML "\t</dependencies>\n";
print XML "</zabbix_export>\n";
close XML;
exit;

