- name: Get task number from branch
  set_fact: task={{ branch | regex_replace('^(.*)/DIRI(.*)$', '\\2') }}

- name: Remove nginx directory
  file:
    path: /home/{{ host_user }}/{{ inventory_hostname }}/nginx/conf.d/{{ task }}
    state: absent

- name: Get host balancer container name
  command: docker ps --filter "name={{ strip_hostname }}_balancer" -q
  register: balancer_container
  ignore_errors: true

- name: Balancer reload
  command: docker exec {{ balancer_container.stdout }} nginx -s reload

- name: Down docker compose
  docker_service:
    project_name: "{{ task }}"
    project_src: /home/{{ user }}/{{ task }}/{{ project_name }}
    state: absent

- name: Remove work directory
  become: yes
  file:
    path: /home/{{ user }}/{{ task }}
    state: absent

- name: Удаление старых образов
  shell: 'docker rmi $(docker images --quiet --filter "dangling=true")'
  ignore_errors: true

- name: Удаление старых volume
  shell: 'docker volume rm $(docker volume ls --quiet --filter "dangling=true")'
  ignore_errors: true

- name: Remove all unused networks
  shell: 'docker network prune -f'
  ignore_errors: true