- name: Install dependencies
  become: yes
  apt: 
    name: "{{ item }}" 
    update_cache: yes 
    state: installed
  with_items:
    - autoconf
    - automake
    - build-essential
    - git
    - lame
    - libsrtp0-dev
    - libspandsp-dev
    - libmyodbc
    - libmysqlclient-dev
    - libgtk2.0-dev
    - libxml2-dev
    - libncurses5-dev
    - libnewt-dev 
    - libsqlite3-dev 
    - libjansson-dev
    - openssl
    - pkg-config 
    - sqlite3 
    - subversion
    - uuid-dev 
    - unixodbc-dev

- name: Install the ODBC
  become: yes
  apt: 
    name: unixodbc 
    state: installed