---

  - name: Install the mysql packages in Debian derivatives
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      - mysql-server
      - mysql-client
      - python-mysqldb
    when: ansible_os_family == 'Debian'

  - name: Create the directory /etc/mysql/conf.d
    file: path=/etc/mysql/conf.d state=directory
    notify:
      - restart mysql

  - name: Start the mysql services
    service: name=mysql state=started enabled=yes

  - name: update mysql root password for all root accounts
    mysql_user: name=root host={{ item }} password={{ mysql_root_db_pass }}
    with_items:
      - 127.0.0.1
      - ::1
      - localhost

  - name: copy .my.cnf file with root password credentials
    template: src=.my.cnf dest=~/.my.cnf mode=0600