- name: Create the database Freeswitch
  mysql_db: 
    name: "{{ item }}"
    state: present
  with_items: "{{ mysql_db_freeswitch }}"

- name: Create the database user Freeswitch
  mysql_user: 
    name: "{{ item.name }}"
    password: "{{ item.pass|default('foobar') }}"
    priv: "{{ item.priv|default('*.*:ALL') }}"
    state: present 
    host: "{{ item.host | default('localhost') }}"
  with_items: "{{ mysql_user_freeswitch }}"