- name: Install Curl
  become: yes
  apt: 
    name: curl 
    state: present

- name: Add dotdeb repo key
  become: yes
  apt_key: 
    url: https://www.dotdeb.org/dotdeb.gpg 
    state: present

- name: Add dotdeb repo
  become: yes
  apt_repository: 
    repo: "deb http://packages.dotdeb.org {{ansible_lsb.codename}} all" 
    state: present 
    update_cache: yes

- name: Install PHP5
  become: yes
  apt: 
    name: "{{ item }}"
    state: present
  with_items:
    - php5-cli
    - php5-ldap
    - php5-mcrypt
    - php5-memcached
    - php5-mysql
    - php-xml
