- name: Create the database user stepan
  become: yes
  mysql_user:
    login_user: root
    login_password: "{{ mysql_root_db_pass }}"
    name: "{{ item.name }}"
    password: "{{ item.pass|default('foobar') }}"
    priv: "{{ item.priv|default('*.*:ALL') }}"
    state: present
    host: "{{ item.host | default('localhost') }}"
  with_items: 
    - "{{ mysql_user_stepan }}"

- name: Bind mysql 0.0.0.0
  become: yes
  lineinfile:
    path: /etc/my.cnf
    insertafter: "^[mysqld]"
    line: "bind-address = 0.0.0.0"
  notify: restart mysql

- name: Create ftp user
  become: yes
  user:
    name: "{{ ftp.user }}"
    password: "{{ ftp.password }}"
    home: "{{ ftp.home }}"
    shell: /sbin/nologin
    group: asterisk