- name: Ensure vsftpd packages are installed
  become: yes
  yum: 
    name: vsftpd 

- name: Place vsftpd configuration file in place.
  become: yes
  template: 
    src: vsftpd.conf.j2 
    dest: /etc/vsftpd/vsftpd.conf
  notify: restart vsftpd

- name: Ensure vsftpd is started and enabled to start at boot.
  become: yes
  service: 
    name: vsftpd 
    state: started 
    enabled: yes