---

  - name: install curl
    apt: name=curl update_cache=yes

  - name: add apt key
    shell: curl https://files.freeswitch.org/repo/deb/debian/freeswitch_archive_g0.pub | apt-key add -

  - name: add repo freeswitch
    shell: echo "deb http://files.freeswitch.org/repo/deb/freeswitch-1.6/ jessie main" > /etc/apt/sources.list.d/freeswitch.list

  - name: install freeswitch
    apt: name="{{ item }}" update_cache=yes
    with_item:
      - freeswitch-meta-all
